### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [SecUSo/privacy-friendly-ruler#5]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1-3:

1. Open Side Drawer
2. Click on Settings
3. Click on:
a. Left Ruler
b. Right Ruler
c. Angle Measure
4. Orientation Change

**Comment by Yonjuni** [comment]
I guess we should just temporary lock the rotation to portrait.

**Comment by Yonjuni** [comment]
Closed #5
