### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [SecUSo/privacy-friendly-ruler#6]
When I perform this sequence of events, the scroll view on screen goes back to the top:

1. Open Side Drawer
2. Click on Help
3. Scroll Down
4. Orientation Change

**Comment by Yonjuni** [comment]
What do you mean by "the scroll view on screen goes back to the top"

**Comment by Yonjuni** [comment]
Okay, I understood. But I close this issue, as it will vanish with an update to our new help structure from PFA design 2.1 (https://github.com/SecUSo/privacy-friendly-app-example).
