### ISSUE TITLE
Added fr (French) translation

### ISSUE THREAD

**Issue by Obsidien** [SecUSo/privacy-friendly-ruler#7]
Testing an application for translating, please check that all looks technically good before pushing.

I have translated your application into `fr` (*French*). Here is the xml:
```xml

```

---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by Yonjuni** [comment]
@Obsidien Thanks for the translation, but the comment does not contain an XML file. Could you make a PR?

**Comment by Yonjuni** [comment]
Closed due to inactivity.
